package dclab.powerdatabackend.dao

import dclab.powerdatabackend.model.Algorithmresult

import org.apache.ibatis.annotations.*
import org.apache.ibatis.type.JdbcType
import org.springframework.stereotype.Repository

@Mapper
@Repository
interface AlgorithmresultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjtudb.algorithmresult
     *
     * @mbg.generated
     */
    @Insert("insert into sjtudb.algorithmresult (hashstr, result, ", "json)", "values (#{hashstr,jdbcType=VARCHAR}, #{result,jdbcType=VARCHAR}, ", "#{json,jdbcType=VARCHAR})")
    fun insert(record: Algorithmresult): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjtudb.algorithmresult
     *
     * @mbg.generated
     */
    @Select("select", "hashstr, result, json", "from sjtudb.algorithmresult")
    @Results(Result(column = "hashstr", property = "hashstr", jdbcType = JdbcType.VARCHAR), Result(column = "result", property = "result", jdbcType = JdbcType.VARCHAR), Result(column = "json", property = "json", jdbcType = JdbcType.VARCHAR))
    fun selectAll(): List<Algorithmresult>
}