package dclab.powerdatabackend.dao;

import dclab.powerdatabackend.model.Baseline;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface BaselineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseline
     *
     * @mbg.generated
     */
    @Insert({
        "insert into baseline (hashstr, json)",
        "values (#{hash,jdbcType=VARCHAR}, #{json,jdbcType=LONGVARCHAR})"
    })
    int insert(Baseline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseline
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "hashstr, json",
        "from baseline"
    })
    @Results({
        @Result(column="hashstr", property="hash", jdbcType=JdbcType.VARCHAR),
        @Result(column="json", property="json", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<Baseline> selectAll();
}