package dclab.powerdatabackend.dao

import dclab.powerdatabackend.model.Cluster

import org.apache.ibatis.annotations.*
import org.apache.ibatis.type.JdbcType
import org.springframework.stereotype.Repository

@Mapper
@Repository
interface ClusterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjtudb.cluster
     *
     * @mbg.generated
     */
    @Insert("insert into sjtudb.cluster (hashstr, json)", "values (#{hashstr,jdbcType=VARCHAR}, #{json,jdbcType=VARCHAR})")
    fun insert(record: Cluster): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjtudb.cluster
     *
     * @mbg.generated
     */
    @Select("select", "hashstr, json", "from sjtudb.cluster")
    @Results(Result(column = "hashstr", property = "hashstr", jdbcType = JdbcType.VARCHAR), Result(column = "json", property = "json", jdbcType = JdbcType.VARCHAR))
    fun selectAll(): List<Cluster>
}