package dclab.powerdatabackend.dao

import dclab.powerdatabackend.model.Concept
import org.apache.ibatis.annotations.*
import org.apache.ibatis.type.JdbcType
import org.springframework.stereotype.Repository

@Mapper
@Repository
interface ConceptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concept
     *
     * @mbg.generated
     */
    @Delete("delete from concept", "where id = #{id,jdbcType=INTEGER}")
    fun deleteByPrimaryKey(id: Int?): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concept
     *
     * @mbg.generated
     */
    @Insert("insert into concept (id, concept, ", "type, createTime, ", "description, englishName, ", "creator)", "values (#{id,jdbcType=INTEGER}, #{concept,jdbcType=VARCHAR}, ", "#{type,jdbcType=VARCHAR}, #{createtime,jdbcType=VARCHAR}, ", "#{description,jdbcType=VARCHAR}, #{englishname,jdbcType=VARCHAR}, ", "#{creator,jdbcType=VARCHAR})")
    fun insert(record: Concept): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concept
     *
     * @mbg.generated
     */
    @Select("select", "id, concept, type, createTime, description, englishName, creator", "from concept", "where id = #{id,jdbcType=INTEGER}")
    @Results(Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true), Result(column = "concept", property = "concept", jdbcType = JdbcType.VARCHAR), Result(column = "type", property = "type", jdbcType = JdbcType.VARCHAR), Result(column = "createTime", property = "createtime", jdbcType = JdbcType.VARCHAR), Result(column = "description", property = "description", jdbcType = JdbcType.VARCHAR), Result(column = "englishName", property = "englishname", jdbcType = JdbcType.VARCHAR), Result(column = "creator", property = "creator", jdbcType = JdbcType.VARCHAR))
    fun selectByPrimaryKey(id: Int?): Concept

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concept
     *
     * @mbg.generated
     */
    @Select("select", "id, concept, type, createTime, description, englishName, creator", "from concept")
    @Results(Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true), Result(column = "concept", property = "concept", jdbcType = JdbcType.VARCHAR), Result(column = "type", property = "type", jdbcType = JdbcType.VARCHAR), Result(column = "createTime", property = "createtime", jdbcType = JdbcType.VARCHAR), Result(column = "description", property = "description", jdbcType = JdbcType.VARCHAR), Result(column = "englishName", property = "englishname", jdbcType = JdbcType.VARCHAR), Result(column = "creator", property = "creator", jdbcType = JdbcType.VARCHAR))
    fun selectAll(): List<Concept>

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concept
     *
     * @mbg.generated
     */
    @Update("update concept", "set concept = #{concept,jdbcType=VARCHAR},", "type = #{type,jdbcType=VARCHAR},", "createTime = #{createtime,jdbcType=VARCHAR},", "description = #{description,jdbcType=VARCHAR},", "englishName = #{englishname,jdbcType=VARCHAR},", "creator = #{creator,jdbcType=VARCHAR}", "where id = #{id,jdbcType=INTEGER}")
    fun updateByPrimaryKey(record: Concept): Int
}