package dclab.powerdatabackend.dao

import dclab.powerdatabackend.model.Concepttype
import org.apache.ibatis.annotations.Delete
import org.apache.ibatis.annotations.Insert
import org.apache.ibatis.annotations.Result
import org.apache.ibatis.annotations.Results
import org.apache.ibatis.annotations.Select
import org.apache.ibatis.type.JdbcType

interface ConcepttypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concepttype
     *
     * @mbg.generated
     */
    @Delete("delete from concepttype", "where conceptType = #{concepttype,jdbcType=VARCHAR}")
    fun deleteByPrimaryKey(concepttype: String): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concepttype
     *
     * @mbg.generated
     */
    @Insert("insert into concepttype (conceptType)", "values (#{concepttype,jdbcType=VARCHAR})")
    fun insert(record: Concepttype): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concepttype
     *
     * @mbg.generated
     */
    @Select("select", "conceptType", "from concepttype")
    @Results(Result(column = "conceptType", property = "concepttype", jdbcType = JdbcType.VARCHAR, id = true))
    fun selectAll(): List<Concepttype>
}