package dclab.powerdatabackend.dao

import dclab.powerdatabackend.model.Correlation

import org.apache.ibatis.annotations.*
import org.apache.ibatis.type.JdbcType
import org.springframework.stereotype.Repository

@Mapper
@Repository
interface CorrelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjtudb.correlation
     *
     * @mbg.generated
     */
    @Insert("insert into sjtudb.correlation (hashstr, result, ", "json)", "values (#{hashstr,jdbcType=VARCHAR}, #{result,jdbcType=VARCHAR}, ", "#{json,jdbcType=VARCHAR})")
    fun insert(record: Correlation): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjtudb.correlation
     *
     * @mbg.generated
     */
    @Select("select", "hashstr, result, json", "from sjtudb.correlation")
    @Results(Result(column = "hashstr", property = "hashstr", jdbcType = JdbcType.VARCHAR), Result(column = "result", property = "result", jdbcType = JdbcType.VARCHAR), Result(column = "json", property = "json", jdbcType = JdbcType.VARCHAR))
    fun selectAll(): List<Correlation>
}