package dclab.powerdatabackend.dao;

import dclab.powerdatabackend.model.Correlation;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface CorrelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table correlation
     *
     * @mbg.generated
     */
    @Insert({
        "insert into correlation (hash, result)",
        "values (#{hash,jdbcType=VARCHAR}, #{result,jdbcType=LONGVARCHAR})"
    })
    int insert(Correlation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table correlation
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "hash, result",
        "from correlation"
    })
    @Results({
        @Result(column="hash", property="hash", jdbcType=JdbcType.VARCHAR),
        @Result(column="result", property="result", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<Correlation> selectAll();
}