package dclab.powerdatabackend.dao

import dclab.powerdatabackend.model.Data

import org.apache.ibatis.annotations.*
import org.apache.ibatis.type.JdbcType
import org.springframework.stereotype.Repository


@Mapper
@Repository
interface DataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjtudb.data
     *
     * @mbg.generated
     */
    @Insert("insert into sjtudb.data (measurepoint, dates, ", "value, locations)", "values (#{measurepoint,jdbcType=VARCHAR}, #{dates,jdbcType=VARCHAR}, ", "#{value,jdbcType=FLOAT}, #{locations,jdbcType=VARCHAR})")
    fun insert(record: Data): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjtudb.data
     *
     * @mbg.generated
     */
    @Select("select", "measurepoint, dates, value, locations", "from sjtudb.data")
    @Results(Result(column = "measurepoint", property = "measurepoint", jdbcType = JdbcType.VARCHAR), Result(column = "dates", property = "dates", jdbcType = JdbcType.VARCHAR), Result(column = "value", property = "value", jdbcType = JdbcType.FLOAT), Result(column = "locations", property = "locations", jdbcType = JdbcType.VARCHAR))
    fun selectAll(): List<Data>
}