package dclab.powerdatabackend.dao

import dclab.powerdatabackend.model.Data
import org.apache.ibatis.annotations.Insert
import org.apache.ibatis.annotations.Result
import org.apache.ibatis.annotations.Results
import org.apache.ibatis.annotations.Select
import org.apache.ibatis.type.JdbcType

interface DataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    @Insert("insert into data (measurePoint, date, ", "value, location)", "values (#{measurepoint,jdbcType=VARCHAR}, #{date,jdbcType=VARCHAR}, ", "#{value,jdbcType=REAL}, #{location,jdbcType=VARCHAR})")
    fun insert(record: Data): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    @Select("select", "measurePoint, date, value, location", "from data")
    @Results(Result(column = "measurePoint", property = "measurepoint", jdbcType = JdbcType.VARCHAR), Result(column = "date", property = "date", jdbcType = JdbcType.VARCHAR), Result(column = "value", property = "value", jdbcType = JdbcType.REAL), Result(column = "location", property = "location", jdbcType = JdbcType.VARCHAR))
    fun selectAll(): List<Data>
}