package dclab.powerdatabackend.dao

import dclab.powerdatabackend.model.File
import org.apache.ibatis.annotations.*
import org.apache.ibatis.type.JdbcType
import org.springframework.stereotype.Repository

@Mapper
@Repository
interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated
     */
    @Delete("delete from file", "where fileID = #{fileid,jdbcType=INTEGER}")
    fun deleteByPrimaryKey(fileid: Int?): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated
     */
    @Insert("insert into file (fileID, fileName, ", "location)", "values (#{fileid,jdbcType=INTEGER}, #{filename,jdbcType=VARCHAR}, ", "#{location,jdbcType=VARCHAR})")
    fun insert(record: File): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated
     */
    @Select("select", "fileID, fileName, location", "from file", "where fileID = #{fileid,jdbcType=INTEGER}")
    @Results(Result(column = "fileID", property = "fileid", jdbcType = JdbcType.INTEGER, id = true), Result(column = "fileName", property = "filename", jdbcType = JdbcType.VARCHAR), Result(column = "location", property = "location", jdbcType = JdbcType.VARCHAR))
    fun selectByPrimaryKey(fileid: Int?): File

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated
     */
    @Select("select", "fileID, fileName, location", "from file")
    @Results(Result(column = "fileID", property = "fileid", jdbcType = JdbcType.INTEGER, id = true), Result(column = "fileName", property = "filename", jdbcType = JdbcType.VARCHAR), Result(column = "location", property = "location", jdbcType = JdbcType.VARCHAR))
    fun selectAll(): List<File>

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated
     */
    @Update("update file", "set fileName = #{filename,jdbcType=VARCHAR},", "location = #{location,jdbcType=VARCHAR}", "where fileID = #{fileid,jdbcType=INTEGER}")
    fun updateByPrimaryKey(record: File): Int
}