package dclab.powerdatabackend.dao

import dclab.powerdatabackend.model.Logictype
import org.apache.ibatis.annotations.*
import org.apache.ibatis.type.JdbcType
import org.springframework.stereotype.Repository

@Mapper
@Repository
interface LogictypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logictype
     *
     * @mbg.generated
     */
    @Delete("delete from logictype", "where logictype = #{logictype,jdbcType=VARCHAR}")
    fun deleteByPrimaryKey(logictype: String): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logictype
     *
     * @mbg.generated
     */
    @Insert("insert into logictype (logictype)", "values (#{logictype,jdbcType=VARCHAR})")
    fun insert(record: Logictype): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logictype
     *
     * @mbg.generated
     */
    @Select("select", "logictype", "from logictype")
    @Results(Result(column = "logictype", property = "logictype", jdbcType = JdbcType.VARCHAR, id = true))
    fun selectAll(): List<Logictype>
}