package dclab.powerdatabackend.dao

import dclab.powerdatabackend.model.Physicstype
import org.apache.ibatis.annotations.*
import org.apache.ibatis.type.JdbcType
import org.springframework.stereotype.Repository

@Mapper
@Repository
interface PhysicstypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table physicstype
     *
     * @mbg.generated
     */
    @Delete("delete from physicstype", "where physicstype = #{physicstype,jdbcType=VARCHAR}")
    fun deleteByPrimaryKey(physicstype: String): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table physicstype
     *
     * @mbg.generated
     */
    @Insert("insert into physicstype (physicstype)", "values (#{physicstype,jdbcType=VARCHAR})")
    fun insert(record: Physicstype): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table physicstype
     *
     * @mbg.generated
     */
    @Select("select", "physicstype", "from physicstype")
    @Results(Result(column = "physicstype", property = "physicstype", jdbcType = JdbcType.VARCHAR, id = true))
    fun selectAll(): List<Physicstype>
}