package dclab.powerdatabackend.dao;

import dclab.powerdatabackend.model.User;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjtudb.user
     *
     * @mbg.generated
     */
    @Insert({
        "insert into sjtudb.user (username, password)",
        "values (#{username,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjtudb.user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "username, password",
        "from sjtudb.user"
    })
    @Results({
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR)
    })
    List<User> selectAll();
}