package dclab.powerdatabackend.model;

public class Algorithmresult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithmresult.hash
     *
     * @mbg.generated
     */
    private String hash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column algorithmresult.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithmresult.hash
     *
     * @return the value of algorithmresult.hash
     *
     * @mbg.generated
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithmresult.hash
     *
     * @param hash the value for algorithmresult.hash
     *
     * @mbg.generated
     */
    public void setHash(String hash) {
        this.hash = hash == null ? null : hash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column algorithmresult.result
     *
     * @return the value of algorithmresult.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column algorithmresult.result
     *
     * @param result the value for algorithmresult.result
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }
}