package dclab.powerdatabackend.model;

public class Baseline {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseline.hash
     *
     * @mbg.generated
     */
    private String hash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseline.json
     *
     * @mbg.generated
     */
    private String json;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseline.hash
     *
     * @return the value of baseline.hash
     *
     * @mbg.generated
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseline.hash
     *
     * @param hash the value for baseline.hash
     *
     * @mbg.generated
     */
    public void setHash(String hash) {
        this.hash = hash == null ? null : hash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseline.json
     *
     * @return the value of baseline.json
     *
     * @mbg.generated
     */
    public String getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseline.json
     *
     * @param json the value for baseline.json
     *
     * @mbg.generated
     */
    public void setJson(String json) {
        this.json = json == null ? null : json.trim();
    }
}