package dclab.powerdatabackend.model;

public class Cluster {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.cluster.hashstr
     *
     * @mbg.generated
     */
    private String hashstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.cluster.json
     *
     * @mbg.generated
     */
    private String json;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.cluster.hashstr
     *
     * @return the value of sjtudb.cluster.hashstr
     *
     * @mbg.generated
     */
    public String getHashstr() {
        return hashstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.cluster.hashstr
     *
     * @param hashstr the value for sjtudb.cluster.hashstr
     *
     * @mbg.generated
     */
    public void setHashstr(String hashstr) {
        this.hashstr = hashstr == null ? null : hashstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.cluster.json
     *
     * @return the value of sjtudb.cluster.json
     *
     * @mbg.generated
     */
    public String getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.cluster.json
     *
     * @param json the value for sjtudb.cluster.json
     *
     * @mbg.generated
     */
    public void setJson(String json) {
        this.json = json == null ? null : json.trim();
    }
}