package dclab.powerdatabackend.model

class Concepttype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column concepttype.conceptType
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column concepttype.conceptType
     *
     * @return the value of concepttype.conceptType
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column concepttype.conceptType
     *
     * @param concepttype the value for concepttype.conceptType
     *
     * @mbg.generated
     */
    var concepttype: String? = null
        set(concepttype) {
            field = concepttype?.trim { it <= ' ' }
        }
}