package dclab.powerdatabackend.model

class Concept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column concept.id
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column concept.id
     *
     * @return the value of concept.id
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column concept.id
     *
     * @param id the value for concept.id
     *
     * @mbg.generated
     */
    var id: Int? = null

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column concept.concept
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column concept.concept
     *
     * @return the value of concept.concept
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column concept.concept
     *
     * @param concept the value for concept.concept
     *
     * @mbg.generated
     */
    var concept: String? = null
        set(concept) {
            field = concept?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column concept.type
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column concept.type
     *
     * @return the value of concept.type
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column concept.type
     *
     * @param type the value for concept.type
     *
     * @mbg.generated
     */
    var type: String? = null
        set(type) {
            field = type?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column concept.createTime
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column concept.createTime
     *
     * @return the value of concept.createTime
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column concept.createTime
     *
     * @param createtime the value for concept.createTime
     *
     * @mbg.generated
     */
    var createtime: String? = null
        set(createtime) {
            field = createtime?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column concept.description
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column concept.description
     *
     * @return the value of concept.description
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column concept.description
     *
     * @param description the value for concept.description
     *
     * @mbg.generated
     */
    var description: String? = null
        set(description) {
            field = description?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column concept.englishName
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column concept.englishName
     *
     * @return the value of concept.englishName
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column concept.englishName
     *
     * @param englishname the value for concept.englishName
     *
     * @mbg.generated
     */
    var englishname: String? = null
        set(englishname) {
            field = englishname?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column concept.creator
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column concept.creator
     *
     * @return the value of concept.creator
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column concept.creator
     *
     * @param creator the value for concept.creator
     *
     * @mbg.generated
     */
    var creator: String? = null
        set(creator) {
            field = creator?.trim { it <= ' ' }
        }
}