package dclab.powerdatabackend.model;

public class Correlation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.correlation.hashstr
     *
     * @mbg.generated
     */
    private String hashstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.correlation.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.correlation.json
     *
     * @mbg.generated
     */
    private String json;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.correlation.hashstr
     *
     * @return the value of sjtudb.correlation.hashstr
     *
     * @mbg.generated
     */
    public String getHashstr() {
        return hashstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.correlation.hashstr
     *
     * @param hashstr the value for sjtudb.correlation.hashstr
     *
     * @mbg.generated
     */
    public void setHashstr(String hashstr) {
        this.hashstr = hashstr == null ? null : hashstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.correlation.result
     *
     * @return the value of sjtudb.correlation.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.correlation.result
     *
     * @param result the value for sjtudb.correlation.result
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.correlation.json
     *
     * @return the value of sjtudb.correlation.json
     *
     * @mbg.generated
     */
    public String getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.correlation.json
     *
     * @param json the value for sjtudb.correlation.json
     *
     * @mbg.generated
     */
    public void setJson(String json) {
        this.json = json == null ? null : json.trim();
    }
}