package dclab.powerdatabackend.model

class Data {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.measurePoint
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.measurePoint
     *
     * @return the value of data.measurePoint
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.measurePoint
     *
     * @param measurepoint the value for data.measurePoint
     *
     * @mbg.generated
     */
    var measurepoint: String? = null
        set(measurepoint) {
            field = measurepoint?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.date
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.date
     *
     * @return the value of data.date
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.date
     *
     * @param date the value for data.date
     *
     * @mbg.generated
     */
    var date: String? = null
        set(date) {
            field = date?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.value
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.value
     *
     * @return the value of data.value
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.value
     *
     * @param value the value for data.value
     *
     * @mbg.generated
     */
    var value: Float? = null

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.location
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.location
     *
     * @return the value of data.location
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.location
     *
     * @param location the value for data.location
     *
     * @mbg.generated
     */
    var location: String? = null
        set(location) {
            field = location?.trim { it <= ' ' }
        }
}