package dclab.powerdatabackend.model;

public class Data {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.data.measurepoint
     *
     * @mbg.generated
     */
    private String measurepoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.data.dates
     *
     * @mbg.generated
     */
    private String dates;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.data.value
     *
     * @mbg.generated
     */
    private Double value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.data.locations
     *
     * @mbg.generated
     */
    private String locations;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.data.measurepoint
     *
     * @return the value of sjtudb.data.measurepoint
     *
     * @mbg.generated
     */
    public String getMeasurepoint() {
        return measurepoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.data.measurepoint
     *
     * @param measurepoint the value for sjtudb.data.measurepoint
     *
     * @mbg.generated
     */
    public void setMeasurepoint(String measurepoint) {
        this.measurepoint = measurepoint == null ? null : measurepoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.data.dates
     *
     * @return the value of sjtudb.data.dates
     *
     * @mbg.generated
     */
    public String getDates() {
        return dates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.data.dates
     *
     * @param dates the value for sjtudb.data.dates
     *
     * @mbg.generated
     */
    public void setDates(String dates) {
        this.dates = dates == null ? null : dates.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.data.value
     *
     * @return the value of sjtudb.data.value
     *
     * @mbg.generated
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.data.value
     *
     * @param value the value for sjtudb.data.value
     *
     * @mbg.generated
     */
    public void setValue(Double value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.data.locations
     *
     * @return the value of sjtudb.data.locations
     *
     * @mbg.generated
     */
    public String getLocations() {
        return locations;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.data.locations
     *
     * @param locations the value for sjtudb.data.locations
     *
     * @mbg.generated
     */
    public void setLocations(String locations) {
        this.locations = locations == null ? null : locations.trim();
    }
}