package dclab.powerdatabackend.model;

public class Datas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.factory
     *
     * @mbg.generated
     */
    private String factory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.line
     *
     * @mbg.generated
     */
    private String line;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.device
     *
     * @mbg.generated
     */
    private String device;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.timestamps
     *
     * @mbg.generated
     */
    private String timestamps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.aphaseelectrictension
     *
     * @mbg.generated
     */
    private Double aphaseelectrictension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.bphaseelectrictension
     *
     * @mbg.generated
     */
    private Double bphaseelectrictension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.cphaseelectrictension
     *
     * @mbg.generated
     */
    private Double cphaseelectrictension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.ablineelectrictension
     *
     * @mbg.generated
     */
    private Double ablineelectrictension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.bclineelectrictension
     *
     * @mbg.generated
     */
    private Double bclineelectrictension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.calineelectrictension
     *
     * @mbg.generated
     */
    private Double calineelectrictension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.aphaseelectriccurrent
     *
     * @mbg.generated
     */
    private Double aphaseelectriccurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.bphaseelectriccurrent
     *
     * @mbg.generated
     */
    private Double bphaseelectriccurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.cphaseelectriccurrent
     *
     * @mbg.generated
     */
    private Double cphaseelectriccurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.zerosequencecurrent
     *
     * @mbg.generated
     */
    private Double zerosequencecurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.aphaseactivepower
     *
     * @mbg.generated
     */
    private Double aphaseactivepower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.bphaseactivepower
     *
     * @mbg.generated
     */
    private Double bphaseactivepower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.cphaseactivepower
     *
     * @mbg.generated
     */
    private Double cphaseactivepower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.threephasetotalactivepower
     *
     * @mbg.generated
     */
    private Double threephasetotalactivepower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.aphasereactivepower
     *
     * @mbg.generated
     */
    private Double aphasereactivepower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.bphasereactivepower
     *
     * @mbg.generated
     */
    private Double bphasereactivepower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.cphasereactivepower
     *
     * @mbg.generated
     */
    private Double cphasereactivepower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.threephasetotalreactivepower
     *
     * @mbg.generated
     */
    private Double threephasetotalreactivepower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.aphaseatpower
     *
     * @mbg.generated
     */
    private Double aphaseatpower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.bphaseatpower
     *
     * @mbg.generated
     */
    private Double bphaseatpower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.cphaseatpower
     *
     * @mbg.generated
     */
    private Double cphaseatpower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.threephasetotalatpower
     *
     * @mbg.generated
     */
    private Double threephasetotalatpower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.aphasepowerfactor
     *
     * @mbg.generated
     */
    private Double aphasepowerfactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.bphasepowerfactor
     *
     * @mbg.generated
     */
    private Double bphasepowerfactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.cphasepowerfactor
     *
     * @mbg.generated
     */
    private Double cphasepowerfactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.averagepowerfactor
     *
     * @mbg.generated
     */
    private Double averagepowerfactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.frequency
     *
     * @mbg.generated
     */
    private Double frequency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.forwardactive
     *
     * @mbg.generated
     */
    private Double forwardactive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.reverseactive
     *
     * @mbg.generated
     */
    private Double reverseactive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.forwardreactivewattage
     *
     * @mbg.generated
     */
    private Double forwardreactivewattage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.reversereactivewattage
     *
     * @mbg.generated
     */
    private Double reversereactivewattage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.voltageunbalance
     *
     * @mbg.generated
     */
    private Double voltageunbalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.electriccurrentunbalance
     *
     * @mbg.generated
     */
    private Double electriccurrentunbalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.aphasevoltageharmonictotaldistortion
     *
     * @mbg.generated
     */
    private Double aphasevoltageharmonictotaldistortion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.bphasevoltageharmonictotaldistortion
     *
     * @mbg.generated
     */
    private Double bphasevoltageharmonictotaldistortion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.cphasevoltageharmonictotaldistortion
     *
     * @mbg.generated
     */
    private Double cphasevoltageharmonictotaldistortion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.totalharmonicdistortionofaphasecurrent
     *
     * @mbg.generated
     */
    private Double totalharmonicdistortionofaphasecurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.totalharmonicdistortionofbphasecurrent
     *
     * @mbg.generated
     */
    private Double totalharmonicdistortionofbphasecurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.totalharmonicdistortionofcphasecurrent
     *
     * @mbg.generated
     */
    private Double totalharmonicdistortionofcphasecurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.maximumpositiveactivedemand
     *
     * @mbg.generated
     */
    private Double maximumpositiveactivedemand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.maximumreverseactivedemand
     *
     * @mbg.generated
     */
    private Double maximumreverseactivedemand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.maximumforwardreactivepowerdemand
     *
     * @mbg.generated
     */
    private Double maximumforwardreactivepowerdemand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sjtudb.datas.maximumreversereactivepowerdemand
     *
     * @mbg.generated
     */
    private Double maximumreversereactivepowerdemand;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.factory
     *
     * @return the value of sjtudb.datas.factory
     *
     * @mbg.generated
     */
    public String getFactory() {
        return factory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.factory
     *
     * @param factory the value for sjtudb.datas.factory
     *
     * @mbg.generated
     */
    public void setFactory(String factory) {
        this.factory = factory == null ? null : factory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.line
     *
     * @return the value of sjtudb.datas.line
     *
     * @mbg.generated
     */
    public String getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.line
     *
     * @param line the value for sjtudb.datas.line
     *
     * @mbg.generated
     */
    public void setLine(String line) {
        this.line = line == null ? null : line.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.device
     *
     * @return the value of sjtudb.datas.device
     *
     * @mbg.generated
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.device
     *
     * @param device the value for sjtudb.datas.device
     *
     * @mbg.generated
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.timestamps
     *
     * @return the value of sjtudb.datas.timestamps
     *
     * @mbg.generated
     */
    public String getTimestamps() {
        return timestamps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.timestamps
     *
     * @param timestamps the value for sjtudb.datas.timestamps
     *
     * @mbg.generated
     */
    public void setTimestamps(String timestamps) {
        this.timestamps = timestamps == null ? null : timestamps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.aphaseelectrictension
     *
     * @return the value of sjtudb.datas.aphaseelectrictension
     *
     * @mbg.generated
     */
    public Double getAphaseelectrictension() {
        return aphaseelectrictension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.aphaseelectrictension
     *
     * @param aphaseelectrictension the value for sjtudb.datas.aphaseelectrictension
     *
     * @mbg.generated
     */
    public void setAphaseelectrictension(Double aphaseelectrictension) {
        this.aphaseelectrictension = aphaseelectrictension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.bphaseelectrictension
     *
     * @return the value of sjtudb.datas.bphaseelectrictension
     *
     * @mbg.generated
     */
    public Double getBphaseelectrictension() {
        return bphaseelectrictension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.bphaseelectrictension
     *
     * @param bphaseelectrictension the value for sjtudb.datas.bphaseelectrictension
     *
     * @mbg.generated
     */
    public void setBphaseelectrictension(Double bphaseelectrictension) {
        this.bphaseelectrictension = bphaseelectrictension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.cphaseelectrictension
     *
     * @return the value of sjtudb.datas.cphaseelectrictension
     *
     * @mbg.generated
     */
    public Double getCphaseelectrictension() {
        return cphaseelectrictension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.cphaseelectrictension
     *
     * @param cphaseelectrictension the value for sjtudb.datas.cphaseelectrictension
     *
     * @mbg.generated
     */
    public void setCphaseelectrictension(Double cphaseelectrictension) {
        this.cphaseelectrictension = cphaseelectrictension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.ablineelectrictension
     *
     * @return the value of sjtudb.datas.ablineelectrictension
     *
     * @mbg.generated
     */
    public Double getAblineelectrictension() {
        return ablineelectrictension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.ablineelectrictension
     *
     * @param ablineelectrictension the value for sjtudb.datas.ablineelectrictension
     *
     * @mbg.generated
     */
    public void setAblineelectrictension(Double ablineelectrictension) {
        this.ablineelectrictension = ablineelectrictension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.bclineelectrictension
     *
     * @return the value of sjtudb.datas.bclineelectrictension
     *
     * @mbg.generated
     */
    public Double getBclineelectrictension() {
        return bclineelectrictension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.bclineelectrictension
     *
     * @param bclineelectrictension the value for sjtudb.datas.bclineelectrictension
     *
     * @mbg.generated
     */
    public void setBclineelectrictension(Double bclineelectrictension) {
        this.bclineelectrictension = bclineelectrictension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.calineelectrictension
     *
     * @return the value of sjtudb.datas.calineelectrictension
     *
     * @mbg.generated
     */
    public Double getCalineelectrictension() {
        return calineelectrictension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.calineelectrictension
     *
     * @param calineelectrictension the value for sjtudb.datas.calineelectrictension
     *
     * @mbg.generated
     */
    public void setCalineelectrictension(Double calineelectrictension) {
        this.calineelectrictension = calineelectrictension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.aphaseelectriccurrent
     *
     * @return the value of sjtudb.datas.aphaseelectriccurrent
     *
     * @mbg.generated
     */
    public Double getAphaseelectriccurrent() {
        return aphaseelectriccurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.aphaseelectriccurrent
     *
     * @param aphaseelectriccurrent the value for sjtudb.datas.aphaseelectriccurrent
     *
     * @mbg.generated
     */
    public void setAphaseelectriccurrent(Double aphaseelectriccurrent) {
        this.aphaseelectriccurrent = aphaseelectriccurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.bphaseelectriccurrent
     *
     * @return the value of sjtudb.datas.bphaseelectriccurrent
     *
     * @mbg.generated
     */
    public Double getBphaseelectriccurrent() {
        return bphaseelectriccurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.bphaseelectriccurrent
     *
     * @param bphaseelectriccurrent the value for sjtudb.datas.bphaseelectriccurrent
     *
     * @mbg.generated
     */
    public void setBphaseelectriccurrent(Double bphaseelectriccurrent) {
        this.bphaseelectriccurrent = bphaseelectriccurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.cphaseelectriccurrent
     *
     * @return the value of sjtudb.datas.cphaseelectriccurrent
     *
     * @mbg.generated
     */
    public Double getCphaseelectriccurrent() {
        return cphaseelectriccurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.cphaseelectriccurrent
     *
     * @param cphaseelectriccurrent the value for sjtudb.datas.cphaseelectriccurrent
     *
     * @mbg.generated
     */
    public void setCphaseelectriccurrent(Double cphaseelectriccurrent) {
        this.cphaseelectriccurrent = cphaseelectriccurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.zerosequencecurrent
     *
     * @return the value of sjtudb.datas.zerosequencecurrent
     *
     * @mbg.generated
     */
    public Double getZerosequencecurrent() {
        return zerosequencecurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.zerosequencecurrent
     *
     * @param zerosequencecurrent the value for sjtudb.datas.zerosequencecurrent
     *
     * @mbg.generated
     */
    public void setZerosequencecurrent(Double zerosequencecurrent) {
        this.zerosequencecurrent = zerosequencecurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.aphaseactivepower
     *
     * @return the value of sjtudb.datas.aphaseactivepower
     *
     * @mbg.generated
     */
    public Double getAphaseactivepower() {
        return aphaseactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.aphaseactivepower
     *
     * @param aphaseactivepower the value for sjtudb.datas.aphaseactivepower
     *
     * @mbg.generated
     */
    public void setAphaseactivepower(Double aphaseactivepower) {
        this.aphaseactivepower = aphaseactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.bphaseactivepower
     *
     * @return the value of sjtudb.datas.bphaseactivepower
     *
     * @mbg.generated
     */
    public Double getBphaseactivepower() {
        return bphaseactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.bphaseactivepower
     *
     * @param bphaseactivepower the value for sjtudb.datas.bphaseactivepower
     *
     * @mbg.generated
     */
    public void setBphaseactivepower(Double bphaseactivepower) {
        this.bphaseactivepower = bphaseactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.cphaseactivepower
     *
     * @return the value of sjtudb.datas.cphaseactivepower
     *
     * @mbg.generated
     */
    public Double getCphaseactivepower() {
        return cphaseactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.cphaseactivepower
     *
     * @param cphaseactivepower the value for sjtudb.datas.cphaseactivepower
     *
     * @mbg.generated
     */
    public void setCphaseactivepower(Double cphaseactivepower) {
        this.cphaseactivepower = cphaseactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.threephasetotalactivepower
     *
     * @return the value of sjtudb.datas.threephasetotalactivepower
     *
     * @mbg.generated
     */
    public Double getThreephasetotalactivepower() {
        return threephasetotalactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.threephasetotalactivepower
     *
     * @param threephasetotalactivepower the value for sjtudb.datas.threephasetotalactivepower
     *
     * @mbg.generated
     */
    public void setThreephasetotalactivepower(Double threephasetotalactivepower) {
        this.threephasetotalactivepower = threephasetotalactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.aphasereactivepower
     *
     * @return the value of sjtudb.datas.aphasereactivepower
     *
     * @mbg.generated
     */
    public Double getAphasereactivepower() {
        return aphasereactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.aphasereactivepower
     *
     * @param aphasereactivepower the value for sjtudb.datas.aphasereactivepower
     *
     * @mbg.generated
     */
    public void setAphasereactivepower(Double aphasereactivepower) {
        this.aphasereactivepower = aphasereactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.bphasereactivepower
     *
     * @return the value of sjtudb.datas.bphasereactivepower
     *
     * @mbg.generated
     */
    public Double getBphasereactivepower() {
        return bphasereactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.bphasereactivepower
     *
     * @param bphasereactivepower the value for sjtudb.datas.bphasereactivepower
     *
     * @mbg.generated
     */
    public void setBphasereactivepower(Double bphasereactivepower) {
        this.bphasereactivepower = bphasereactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.cphasereactivepower
     *
     * @return the value of sjtudb.datas.cphasereactivepower
     *
     * @mbg.generated
     */
    public Double getCphasereactivepower() {
        return cphasereactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.cphasereactivepower
     *
     * @param cphasereactivepower the value for sjtudb.datas.cphasereactivepower
     *
     * @mbg.generated
     */
    public void setCphasereactivepower(Double cphasereactivepower) {
        this.cphasereactivepower = cphasereactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.threephasetotalreactivepower
     *
     * @return the value of sjtudb.datas.threephasetotalreactivepower
     *
     * @mbg.generated
     */
    public Double getThreephasetotalreactivepower() {
        return threephasetotalreactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.threephasetotalreactivepower
     *
     * @param threephasetotalreactivepower the value for sjtudb.datas.threephasetotalreactivepower
     *
     * @mbg.generated
     */
    public void setThreephasetotalreactivepower(Double threephasetotalreactivepower) {
        this.threephasetotalreactivepower = threephasetotalreactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.aphaseatpower
     *
     * @return the value of sjtudb.datas.aphaseatpower
     *
     * @mbg.generated
     */
    public Double getAphaseatpower() {
        return aphaseatpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.aphaseatpower
     *
     * @param aphaseatpower the value for sjtudb.datas.aphaseatpower
     *
     * @mbg.generated
     */
    public void setAphaseatpower(Double aphaseatpower) {
        this.aphaseatpower = aphaseatpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.bphaseatpower
     *
     * @return the value of sjtudb.datas.bphaseatpower
     *
     * @mbg.generated
     */
    public Double getBphaseatpower() {
        return bphaseatpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.bphaseatpower
     *
     * @param bphaseatpower the value for sjtudb.datas.bphaseatpower
     *
     * @mbg.generated
     */
    public void setBphaseatpower(Double bphaseatpower) {
        this.bphaseatpower = bphaseatpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.cphaseatpower
     *
     * @return the value of sjtudb.datas.cphaseatpower
     *
     * @mbg.generated
     */
    public Double getCphaseatpower() {
        return cphaseatpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.cphaseatpower
     *
     * @param cphaseatpower the value for sjtudb.datas.cphaseatpower
     *
     * @mbg.generated
     */
    public void setCphaseatpower(Double cphaseatpower) {
        this.cphaseatpower = cphaseatpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.threephasetotalatpower
     *
     * @return the value of sjtudb.datas.threephasetotalatpower
     *
     * @mbg.generated
     */
    public Double getThreephasetotalatpower() {
        return threephasetotalatpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.threephasetotalatpower
     *
     * @param threephasetotalatpower the value for sjtudb.datas.threephasetotalatpower
     *
     * @mbg.generated
     */
    public void setThreephasetotalatpower(Double threephasetotalatpower) {
        this.threephasetotalatpower = threephasetotalatpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.aphasepowerfactor
     *
     * @return the value of sjtudb.datas.aphasepowerfactor
     *
     * @mbg.generated
     */
    public Double getAphasepowerfactor() {
        return aphasepowerfactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.aphasepowerfactor
     *
     * @param aphasepowerfactor the value for sjtudb.datas.aphasepowerfactor
     *
     * @mbg.generated
     */
    public void setAphasepowerfactor(Double aphasepowerfactor) {
        this.aphasepowerfactor = aphasepowerfactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.bphasepowerfactor
     *
     * @return the value of sjtudb.datas.bphasepowerfactor
     *
     * @mbg.generated
     */
    public Double getBphasepowerfactor() {
        return bphasepowerfactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.bphasepowerfactor
     *
     * @param bphasepowerfactor the value for sjtudb.datas.bphasepowerfactor
     *
     * @mbg.generated
     */
    public void setBphasepowerfactor(Double bphasepowerfactor) {
        this.bphasepowerfactor = bphasepowerfactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.cphasepowerfactor
     *
     * @return the value of sjtudb.datas.cphasepowerfactor
     *
     * @mbg.generated
     */
    public Double getCphasepowerfactor() {
        return cphasepowerfactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.cphasepowerfactor
     *
     * @param cphasepowerfactor the value for sjtudb.datas.cphasepowerfactor
     *
     * @mbg.generated
     */
    public void setCphasepowerfactor(Double cphasepowerfactor) {
        this.cphasepowerfactor = cphasepowerfactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.averagepowerfactor
     *
     * @return the value of sjtudb.datas.averagepowerfactor
     *
     * @mbg.generated
     */
    public Double getAveragepowerfactor() {
        return averagepowerfactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.averagepowerfactor
     *
     * @param averagepowerfactor the value for sjtudb.datas.averagepowerfactor
     *
     * @mbg.generated
     */
    public void setAveragepowerfactor(Double averagepowerfactor) {
        this.averagepowerfactor = averagepowerfactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.frequency
     *
     * @return the value of sjtudb.datas.frequency
     *
     * @mbg.generated
     */
    public Double getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.frequency
     *
     * @param frequency the value for sjtudb.datas.frequency
     *
     * @mbg.generated
     */
    public void setFrequency(Double frequency) {
        this.frequency = frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.forwardactive
     *
     * @return the value of sjtudb.datas.forwardactive
     *
     * @mbg.generated
     */
    public Double getForwardactive() {
        return forwardactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.forwardactive
     *
     * @param forwardactive the value for sjtudb.datas.forwardactive
     *
     * @mbg.generated
     */
    public void setForwardactive(Double forwardactive) {
        this.forwardactive = forwardactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.reverseactive
     *
     * @return the value of sjtudb.datas.reverseactive
     *
     * @mbg.generated
     */
    public Double getReverseactive() {
        return reverseactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.reverseactive
     *
     * @param reverseactive the value for sjtudb.datas.reverseactive
     *
     * @mbg.generated
     */
    public void setReverseactive(Double reverseactive) {
        this.reverseactive = reverseactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.forwardreactivewattage
     *
     * @return the value of sjtudb.datas.forwardreactivewattage
     *
     * @mbg.generated
     */
    public Double getForwardreactivewattage() {
        return forwardreactivewattage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.forwardreactivewattage
     *
     * @param forwardreactivewattage the value for sjtudb.datas.forwardreactivewattage
     *
     * @mbg.generated
     */
    public void setForwardreactivewattage(Double forwardreactivewattage) {
        this.forwardreactivewattage = forwardreactivewattage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.reversereactivewattage
     *
     * @return the value of sjtudb.datas.reversereactivewattage
     *
     * @mbg.generated
     */
    public Double getReversereactivewattage() {
        return reversereactivewattage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.reversereactivewattage
     *
     * @param reversereactivewattage the value for sjtudb.datas.reversereactivewattage
     *
     * @mbg.generated
     */
    public void setReversereactivewattage(Double reversereactivewattage) {
        this.reversereactivewattage = reversereactivewattage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.voltageunbalance
     *
     * @return the value of sjtudb.datas.voltageunbalance
     *
     * @mbg.generated
     */
    public Double getVoltageunbalance() {
        return voltageunbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.voltageunbalance
     *
     * @param voltageunbalance the value for sjtudb.datas.voltageunbalance
     *
     * @mbg.generated
     */
    public void setVoltageunbalance(Double voltageunbalance) {
        this.voltageunbalance = voltageunbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.electriccurrentunbalance
     *
     * @return the value of sjtudb.datas.electriccurrentunbalance
     *
     * @mbg.generated
     */
    public Double getElectriccurrentunbalance() {
        return electriccurrentunbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.electriccurrentunbalance
     *
     * @param electriccurrentunbalance the value for sjtudb.datas.electriccurrentunbalance
     *
     * @mbg.generated
     */
    public void setElectriccurrentunbalance(Double electriccurrentunbalance) {
        this.electriccurrentunbalance = electriccurrentunbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.aphasevoltageharmonictotaldistortion
     *
     * @return the value of sjtudb.datas.aphasevoltageharmonictotaldistortion
     *
     * @mbg.generated
     */
    public Double getAphasevoltageharmonictotaldistortion() {
        return aphasevoltageharmonictotaldistortion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.aphasevoltageharmonictotaldistortion
     *
     * @param aphasevoltageharmonictotaldistortion the value for sjtudb.datas.aphasevoltageharmonictotaldistortion
     *
     * @mbg.generated
     */
    public void setAphasevoltageharmonictotaldistortion(Double aphasevoltageharmonictotaldistortion) {
        this.aphasevoltageharmonictotaldistortion = aphasevoltageharmonictotaldistortion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.bphasevoltageharmonictotaldistortion
     *
     * @return the value of sjtudb.datas.bphasevoltageharmonictotaldistortion
     *
     * @mbg.generated
     */
    public Double getBphasevoltageharmonictotaldistortion() {
        return bphasevoltageharmonictotaldistortion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.bphasevoltageharmonictotaldistortion
     *
     * @param bphasevoltageharmonictotaldistortion the value for sjtudb.datas.bphasevoltageharmonictotaldistortion
     *
     * @mbg.generated
     */
    public void setBphasevoltageharmonictotaldistortion(Double bphasevoltageharmonictotaldistortion) {
        this.bphasevoltageharmonictotaldistortion = bphasevoltageharmonictotaldistortion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.cphasevoltageharmonictotaldistortion
     *
     * @return the value of sjtudb.datas.cphasevoltageharmonictotaldistortion
     *
     * @mbg.generated
     */
    public Double getCphasevoltageharmonictotaldistortion() {
        return cphasevoltageharmonictotaldistortion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.cphasevoltageharmonictotaldistortion
     *
     * @param cphasevoltageharmonictotaldistortion the value for sjtudb.datas.cphasevoltageharmonictotaldistortion
     *
     * @mbg.generated
     */
    public void setCphasevoltageharmonictotaldistortion(Double cphasevoltageharmonictotaldistortion) {
        this.cphasevoltageharmonictotaldistortion = cphasevoltageharmonictotaldistortion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.totalharmonicdistortionofaphasecurrent
     *
     * @return the value of sjtudb.datas.totalharmonicdistortionofaphasecurrent
     *
     * @mbg.generated
     */
    public Double getTotalharmonicdistortionofaphasecurrent() {
        return totalharmonicdistortionofaphasecurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.totalharmonicdistortionofaphasecurrent
     *
     * @param totalharmonicdistortionofaphasecurrent the value for sjtudb.datas.totalharmonicdistortionofaphasecurrent
     *
     * @mbg.generated
     */
    public void setTotalharmonicdistortionofaphasecurrent(Double totalharmonicdistortionofaphasecurrent) {
        this.totalharmonicdistortionofaphasecurrent = totalharmonicdistortionofaphasecurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.totalharmonicdistortionofbphasecurrent
     *
     * @return the value of sjtudb.datas.totalharmonicdistortionofbphasecurrent
     *
     * @mbg.generated
     */
    public Double getTotalharmonicdistortionofbphasecurrent() {
        return totalharmonicdistortionofbphasecurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.totalharmonicdistortionofbphasecurrent
     *
     * @param totalharmonicdistortionofbphasecurrent the value for sjtudb.datas.totalharmonicdistortionofbphasecurrent
     *
     * @mbg.generated
     */
    public void setTotalharmonicdistortionofbphasecurrent(Double totalharmonicdistortionofbphasecurrent) {
        this.totalharmonicdistortionofbphasecurrent = totalharmonicdistortionofbphasecurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.totalharmonicdistortionofcphasecurrent
     *
     * @return the value of sjtudb.datas.totalharmonicdistortionofcphasecurrent
     *
     * @mbg.generated
     */
    public Double getTotalharmonicdistortionofcphasecurrent() {
        return totalharmonicdistortionofcphasecurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.totalharmonicdistortionofcphasecurrent
     *
     * @param totalharmonicdistortionofcphasecurrent the value for sjtudb.datas.totalharmonicdistortionofcphasecurrent
     *
     * @mbg.generated
     */
    public void setTotalharmonicdistortionofcphasecurrent(Double totalharmonicdistortionofcphasecurrent) {
        this.totalharmonicdistortionofcphasecurrent = totalharmonicdistortionofcphasecurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.maximumpositiveactivedemand
     *
     * @return the value of sjtudb.datas.maximumpositiveactivedemand
     *
     * @mbg.generated
     */
    public Double getMaximumpositiveactivedemand() {
        return maximumpositiveactivedemand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.maximumpositiveactivedemand
     *
     * @param maximumpositiveactivedemand the value for sjtudb.datas.maximumpositiveactivedemand
     *
     * @mbg.generated
     */
    public void setMaximumpositiveactivedemand(Double maximumpositiveactivedemand) {
        this.maximumpositiveactivedemand = maximumpositiveactivedemand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.maximumreverseactivedemand
     *
     * @return the value of sjtudb.datas.maximumreverseactivedemand
     *
     * @mbg.generated
     */
    public Double getMaximumreverseactivedemand() {
        return maximumreverseactivedemand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.maximumreverseactivedemand
     *
     * @param maximumreverseactivedemand the value for sjtudb.datas.maximumreverseactivedemand
     *
     * @mbg.generated
     */
    public void setMaximumreverseactivedemand(Double maximumreverseactivedemand) {
        this.maximumreverseactivedemand = maximumreverseactivedemand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.maximumforwardreactivepowerdemand
     *
     * @return the value of sjtudb.datas.maximumforwardreactivepowerdemand
     *
     * @mbg.generated
     */
    public Double getMaximumforwardreactivepowerdemand() {
        return maximumforwardreactivepowerdemand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.maximumforwardreactivepowerdemand
     *
     * @param maximumforwardreactivepowerdemand the value for sjtudb.datas.maximumforwardreactivepowerdemand
     *
     * @mbg.generated
     */
    public void setMaximumforwardreactivepowerdemand(Double maximumforwardreactivepowerdemand) {
        this.maximumforwardreactivepowerdemand = maximumforwardreactivepowerdemand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sjtudb.datas.maximumreversereactivepowerdemand
     *
     * @return the value of sjtudb.datas.maximumreversereactivepowerdemand
     *
     * @mbg.generated
     */
    public Double getMaximumreversereactivepowerdemand() {
        return maximumreversereactivepowerdemand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sjtudb.datas.maximumreversereactivepowerdemand
     *
     * @param maximumreversereactivepowerdemand the value for sjtudb.datas.maximumreversereactivepowerdemand
     *
     * @mbg.generated
     */
    public void setMaximumreversereactivepowerdemand(Double maximumreversereactivepowerdemand) {
        this.maximumreversereactivepowerdemand = maximumreversereactivepowerdemand;
    }
}