package dclab.powerdatabackend.model

class File {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.fileID
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.fileID
     *
     * @return the value of file.fileID
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.fileID
     *
     * @param fileid the value for file.fileID
     *
     * @mbg.generated
     */
    var fileid: Int? = null

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.fileName
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.fileName
     *
     * @return the value of file.fileName
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.fileName
     *
     * @param filename the value for file.fileName
     *
     * @mbg.generated
     */
    var filename: String? = null
        set(filename) {
            field = filename?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.location
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.location
     *
     * @return the value of file.location
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.location
     *
     * @param location the value for file.location
     *
     * @mbg.generated
     */
    var location: String? = null
        set(location) {
            field = location?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.type
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.type
     *
     * @return the value of file.type
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.type
     *
     * @param type the value for file.type
     *
     * @mbg.generated
     */
    var type: String? = null
        set(type) {
            field = type?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.creator
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.creator
     *
     * @return the value of file.creator
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.creator
     *
     * @param creator the value for file.creator
     *
     * @mbg.generated
     */
    var creator: String? = null
        set(creator) {
            field = creator?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.createTime
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.createTime
     *
     * @return the value of file.createTime
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.createTime
     *
     * @param createtime the value for file.createTime
     *
     * @mbg.generated
     */
    var createtime: String? = null
        set(createtime) {
            field = createtime?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.size
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.size
     *
     * @return the value of file.size
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.size
     *
     * @param size the value for file.size
     *
     * @mbg.generated
     */
    var size: String? = null
        set(size) {
            field = size?.trim { it <= ' ' }
        }
}