package dclab.powerdatabackend.model

class Logic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logic.logic
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logic.logic
     *
     * @return the value of logic.logic
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logic.logic
     *
     * @param logic the value for logic.logic
     *
     * @mbg.generated
     */
    var logic: String? = null
        set(logic) {
            field = logic?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logic.concept
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logic.concept
     *
     * @return the value of logic.concept
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logic.concept
     *
     * @param concept the value for logic.concept
     *
     * @mbg.generated
     */
    var concept: String? = null
        set(concept) {
            field = concept?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logic.createTime
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logic.createTime
     *
     * @return the value of logic.createTime
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logic.createTime
     *
     * @param createtime the value for logic.createTime
     *
     * @mbg.generated
     */
    var createtime: String? = null
        set(createtime) {
            field = createtime?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logic.description
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logic.description
     *
     * @return the value of logic.description
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logic.description
     *
     * @param description the value for logic.description
     *
     * @mbg.generated
     */
    var description: String? = null
        set(description) {
            field = description?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logic.type
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logic.type
     *
     * @return the value of logic.type
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logic.type
     *
     * @param type the value for logic.type
     *
     * @mbg.generated
     */
    var type: String? = null
        set(type) {
            field = type?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logic.englishName
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logic.englishName
     *
     * @return the value of logic.englishName
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logic.englishName
     *
     * @param englishname the value for logic.englishName
     *
     * @mbg.generated
     */
    var englishname: String? = null
        set(englishname) {
            field = englishname?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logic.creator
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logic.creator
     *
     * @return the value of logic.creator
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logic.creator
     *
     * @param creator the value for logic.creator
     *
     * @mbg.generated
     */
    var creator: String? = null
        set(creator) {
            field = creator?.trim { it <= ' ' }
        }
}