package dclab.powerdatabackend.model

class Logictype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logictype.logictype
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logictype.logictype
     *
     * @return the value of logictype.logictype
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logictype.logictype
     *
     * @param logictype the value for logictype.logictype
     *
     * @mbg.generated
     */
    var logictype: String? = null
        set(logictype) {
            field = logictype?.trim { it <= ' ' }
        }
}