package dclab.powerdatabackend.model

class Physicstype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physicstype.physicstype
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column physicstype.physicstype
     *
     * @return the value of physicstype.physicstype
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physicstype.physicstype
     *
     * @param physicstype the value for physicstype.physicstype
     *
     * @mbg.generated
     */
    var physicstype: String? = null
        set(physicstype) {
            field = physicstype?.trim { it <= ' ' }
        }
}