package dclab.powerdatabackend.model

class Physics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physics.physics
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column physics.physics
     *
     * @return the value of physics.physics
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physics.physics
     *
     * @param physics the value for physics.physics
     *
     * @mbg.generated
     */
    var physics: String? = null
        set(physics) {
            field = physics?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physics.type
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column physics.type
     *
     * @return the value of physics.type
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physics.type
     *
     * @param type the value for physics.type
     *
     * @mbg.generated
     */
    var type: String? = null
        set(type) {
            field = type?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physics.description
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column physics.description
     *
     * @return the value of physics.description
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physics.description
     *
     * @param description the value for physics.description
     *
     * @mbg.generated
     */
    var description: String? = null
        set(description) {
            field = description?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physics.createTime
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column physics.createTime
     *
     * @return the value of physics.createTime
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physics.createTime
     *
     * @param createtime the value for physics.createTime
     *
     * @mbg.generated
     */
    var createtime: String? = null
        set(createtime) {
            field = createtime?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physics.logic
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column physics.logic
     *
     * @return the value of physics.logic
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physics.logic
     *
     * @param logic the value for physics.logic
     *
     * @mbg.generated
     */
    var logic: String? = null
        set(logic) {
            field = logic?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physics.englishName
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column physics.englishName
     *
     * @return the value of physics.englishName
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physics.englishName
     *
     * @param englishname the value for physics.englishName
     *
     * @mbg.generated
     */
    var englishname: String? = null
        set(englishname) {
            field = englishname?.trim { it <= ' ' }
        }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physics.creator
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column physics.creator
     *
     * @return the value of physics.creator
     *
     * @mbg.generated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physics.creator
     *
     * @param creator the value for physics.creator
     *
     * @mbg.generated
     */
    var creator: String? = null
        set(creator) {
            field = creator?.trim { it <= ' ' }
        }
}